# Generated by Django 5.0.3 on 2024-03-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beritaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beritamodel',
            name='author',
            field=models.CharField(default='Author', max_length=200),
        ),
    ]
